In [1]:
import pandas as pd

# Task1

###### Створіть DataFrame з не менш ніж шістьма рядками.
###### Виведіть увесь DataFrame.
###### Визначте середню ціну книг.
###### Знайдіть книги, видані після 2015 року.
###### Відсортуйте DataFrame за ціною в порядку зростання.

In [2]:
df1 = pd.DataFrame({
    "Title": ["Python Basics", "Data Science 101", "AI Revolution", "Old Algorithms", "Web Development", "Machine Learning"],
    "Author": ["John Smith", "Anna Brown", "Mark Lee", "Ivan Petrov", "Lisa White", "Tom Green"],
    "Year": [2018, 2020, 2022, 2010, 2017, 2019],
    "Price": [25, 30, 45, 20, 35, 50]
})
df1

              Title       Author  Year  Price
0     Python Basics   John Smith  2018     25
1  Data Science 101   Anna Brown  2020     30
2     AI Revolution     Mark Lee  2022     45
3    Old Algorithms  Ivan Petrov  2010     20
4   Web Development   Lisa White  2017     35
5  Machine Learning    Tom Green  2019     50

In [3]:
print(f'Price mean: {df1["Price"].mean()}')

Price mean: 34.166666666666664

In [5]:
df1[df1["Year"] > 2015]

              Title      Author  Year  Price
0     Python Basics  John Smith  2018     25
1  Data Science 101  Anna Brown  2020     30
2     AI Revolution    Mark Lee  2022     45
4   Web Development  Lisa White  2017     35
5  Machine Learning   Tom Green  2019     50

In [7]:
df1.sort_values(by="Price")

              Title       Author  Year  Price
3    Old Algorithms  Ivan Petrov  2010     20
0     Python Basics   John Smith  2018     25
1  Data Science 101   Anna Brown  2020     30
4   Web Development   Lisa White  2017     35
2     AI Revolution     Mark Lee  2022     45
5  Machine Learning    Tom Green  2019     50

# Task2

###### У CSV-файлі містяться дані про замовлення: "Номер замовлення", "Клієнт", "Дата", "Сума".
###### Прочитайте дані з файлу в DataFrame.
###### Виведіть перші десять рядків.
###### Визначте кількість замовлень кожного клієнта.
###### Знайдіть максимальну та мінімальну суми замовлень.
###### Підрахуйте загальну суму всіх замовлень.

In [9]:
df2 = pd.read_csv("orders.csv")
df2.head(10)

   Order ID Customer        Date  Amount
0      1001     Ivan  2024-01-10     250
1      1002    Olena  2024-01-11     300
2      1003     Ivan  2024-01-12     150
3      1004    Maria  2024-01-13     400
4      1005    Olena  2024-01-14     500
5      1006    Petro  2024-01-15     200
6      1007    Maria  2024-01-16     350
7      1008     Ivan  2024-01-17     450
8      1009    Petro  2024-01-18     300
9      1010    Olena  2024-01-19     250

In [13]:
print(f"Max order amount: {df2["Amount"].max()}")
print(f"Min order amount: {df2["Amount"].min()}")

Max order amount: 700
Min order amount: 150

In [14]:
print(f"Total sum of orders: {df2["Amount"].sum()}")

Total sum of orders: 4450

In [16]:
print("\nOrders count per customer:")
print(df2["Customer"].value_counts())

Orders count per customer:
Customer
Ivan     4
Olena    3
Maria    3
Petro    2
Name: count, dtype: int64

# Task3

###### Є таблиця з даними про продукти харчування: "Продукт", "Категорія", "Калорії", "Білки".
###### Створіть DataFrame з не менш ніж десятьма рядками.
###### Виведіть увесь DataFrame.
###### Знайдіть усі продукти з калорійністю вище 300.
###### Підрахуйте середню кількість білків за категоріями.
###### Відсортуйте DataFrame за калорійністю в порядку убування.

In [17]:
df3 = pd.DataFrame({
    "Product": ["Apple", "Banana", "Chicken", "Beef", "Cheese", "Milk", "Bread", "Rice", "Chocolate", "Nuts"],
    "Category": ["Fruits", "Fruits", "Meat", "Meat", "Dairy", "Dairy", "Grains", "Grains", "Sweets", "Snacks"],
    "Calories": [52, 96, 239, 250, 402, 60, 265, 130, 546, 607],
    "Protein": [0.3, 1.3, 27, 26, 25, 3.2, 9, 2.7, 4.9, 20]
})
df3

     Product Category  Calories  Protein
0      Apple   Fruits        52      0.3
1     Banana   Fruits        96      1.3
2    Chicken     Meat       239     27.0
3       Beef     Meat       250     26.0
4     Cheese    Dairy       402     25.0
5       Milk    Dairy        60      3.2
6      Bread   Grains       265      9.0
7       Rice   Grains       130      2.7
8  Chocolate   Sweets       546      4.9
9       Nuts   Snacks       607     20.0

In [18]:
df3[df3["Calories"] > 300]

     Product Category  Calories  Protein
4     Cheese    Dairy       402     25.0
8  Chocolate   Sweets       546      4.9
9       Nuts   Snacks       607     20.0

In [19]:
print("Average protein by category:")
print(df3.groupby("Category")["Protein"].mean())

Average protein by category:
Category
Dairy     14.10
Fruits     0.80
Grains     5.85
Meat      26.50
Snacks    20.00
Sweets     4.90
Name: Protein, dtype: float64

In [20]:
df3.sort_values(by="Calories", ascending=False)

     Product Category  Calories  Protein
9       Nuts   Snacks       607     20.0
8  Chocolate   Sweets       546      4.9
4     Cheese    Dairy       402     25.0
6      Bread   Grains       265      9.0
3       Beef     Meat       250     26.0
2    Chicken     Meat       239     27.0
7       Rice   Grains       130      2.7
1     Banana   Fruits        96      1.3
5       Milk    Dairy        60      3.2
0      Apple   Fruits        52      0.3

# Task4

###### Зібрано дані про співробітників та їхні проекти: "Ім'я", "Проект", "Години".
###### Створіть DataFrame з не менш ніж вісьмома рядками.
###### Виведіть вихідний DataFrame.
###### Підрахуйте загальну кількість годин за кожним співробітником.
###### Підрахуйте загальну кількість годин за кожним проектом.
###### Знайдіть співробітника, який витратив найбільше годин.

In [21]:
df4 = pd.DataFrame({
    "Name": ["Ivan", "Olena", "Maria", "Petro", "Ivan", "Olena", "Maria", "Petro"],
    "Project": ["AI System", "Web App", "AI System", "Mobile App", "Web App", "AI System", "Mobile App", "Web App"],
    "Hours": [30, 25, 40, 20, 15, 35, 10, 45]
})
df4

    Name     Project  Hours
0   Ivan   AI System     30
1  Olena     Web App     25
2  Maria   AI System     40
3  Petro  Mobile App     20
4   Ivan     Web App     15
5  Olena   AI System     35
6  Maria  Mobile App     10
7  Petro     Web App     45

In [24]:
df4.groupby("Name")["Hours"].sum()

Name
Ivan     45
Maria    50
Olena    60
Petro    65
Name: Hours, dtype: int64

In [25]:
df4.groupby("Project")["Hours"].sum()

Project
AI System     105
Mobile App     30
Web App        85
Name: Hours, dtype: int64

In [26]:
df4.groupby("Name")["Hours"].max()

Name
Ivan     30
Maria    40
Olena    35
Petro    45
Name: Hours, dtype: int64

In [30]:
print(f"Employee with most hours: {df4.groupby("Name")["Hours"].sum().idxmax()}")

Employee with most hours: Petro

# Task5

###### У вас є таблиця продажів квитків: "Фільм", "Місто", "Продані квитки".
###### Створіть DataFrame з не менш ніж дванадцятьма рядками.
###### Виведіть увесь DataFrame.
###### Підрахуйте загальну кількість проданих квитків за кожним фільмом.
###### Підрахуйте загальну кількість квитків по кожному місту.
###### Знайдіть фільм із найбільшою кількістю продажів.

In [31]:
df5 = pd.DataFrame({
    "Movie": ["Avatar","Avatar","Avatar","Titanic","Titanic","Titanic","Inception","Inception","Inception","Matrix","Matrix","Matrix"],
    "City": ["Kyiv","Lviv","Odesa","Kyiv","Lviv","Odesa","Kyiv","Lviv","Odesa","Kyiv","Lviv","Odesa"],
    "Tickets Sold": [120,80,100,90,70,60,110,95,85,130,75,65]
})
df5

        Movie   City  Tickets Sold
0      Avatar   Kyiv           120
1      Avatar   Lviv            80
2      Avatar  Odesa           100
3     Titanic   Kyiv            90
4     Titanic   Lviv            70
5     Titanic  Odesa            60
6   Inception   Kyiv           110
7   Inception   Lviv            95
8   Inception  Odesa            85
9      Matrix   Kyiv           130
10     Matrix   Lviv            75
11     Matrix  Odesa            65

In [32]:
df5.groupby("City")["Tickets Sold"].sum()

City
Kyiv     450
Lviv     320
Odesa    310
Name: Tickets Sold, dtype: int64

In [33]:
df5.groupby("Movie")["Tickets Sold"].sum()

Movie
Avatar       300
Inception    290
Matrix       270
Titanic      220
Name: Tickets Sold, dtype: int64

In [34]:
print(f"Movie with most sold tickets: {df5.groupby("Movie")["Tickets Sold"].sum().idxmax()}")

Movie with most sold tickets: Avatar

# Task6

###### Дано дві таблиці: перша з інформацією про клієнтів ("ID", "Ім'я", "Місто"), друга — з їхніми замовленнями ("ID клієнта", "Замовлення", "Вартість").
###### Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками кожен.
###### Виведіть обидва DataFrame.
###### Об'єднайте їх за ідентифікатором клієнта.
###### Підрахуйте загальну вартість замовлень за кожним клієнтом.
###### Виведіть результат у вигляді нового DataFrame.

In [35]:
clients = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Ivan", "Olena", "Maria", "Petro", "Anna"],
    "City": ["Kyiv", "Lviv", "Odesa", "Kharkiv", "Dnipro"]
})
orders = pd.DataFrame({
    "Client ID": [1, 2, 3, 1, 4, 5, 2],
    "Order": ["Laptop", "Phone", "Tablet", "Mouse", "Monitor", "Keyboard", "Headset"],
    "Cost": [1000, 700, 500, 50, 300, 150, 200]
})

In [36]:
clients

   ID   Name     City
0   1   Ivan     Kyiv
1   2  Olena     Lviv
2   3  Maria    Odesa
3   4  Petro  Kharkiv
4   5   Anna   Dnipro

In [37]:
orders

   Client ID     Order  Cost
0          1    Laptop  1000
1          2     Phone   700
2          3    Tablet   500
3          1     Mouse    50
4          4   Monitor   300
5          5  Keyboard   150
6          2   Headset   200

In [38]:
df6 = pd.merge(clients, orders, left_on="ID", right_on="Client ID")
df6

   ID   Name     City  Client ID     Order  Cost
0   1   Ivan     Kyiv          1    Laptop  1000
1   1   Ivan     Kyiv          1     Mouse    50
2   2  Olena     Lviv          2     Phone   700
3   2  Olena     Lviv          2   Headset   200
4   3  Maria    Odesa          3    Tablet   500
5   4  Petro  Kharkiv          4   Monitor   300
6   5   Anna   Dnipro          5  Keyboard   150

In [39]:
df6_2 = df6.groupby("Name")["Cost"].sum()
df6_2

Name
Anna      150
Ivan     1050
Maria     500
Olena     900
Petro     300
Name: Cost, dtype: int64