In [1]:
import pandas as pd

# Task1

#### У вас є дані про користувачів із полями: "Ім'я", "Вік" і "Місто".
#### Створіть DataFrame зі словника Python із п'ятьма записами.
#### Виведіть весь DataFrame.
#### Визначте кількість рядків і стовпців.
#### Виведіть назви всіх стовпців.
#### Покажіть перші три рядки таблиці.

In [4]:
df = pd.DataFrame({
    "name": ["Cement", "Nikita", "Kiril", "Artur", "John"],
    "age": [17, 14, 19, 15, 18],
    "city": ["Kyiv", "Paris", "Kharkiv", "Berlin", "Washington"]
})
df

     name  age        city
0  Cement   17        Kyiv
1  Nikita   14       Paris
2   Kiril   19     Kharkiv
3   Artur   15      Berlin
4    John   18  Washington

In [7]:
columns = df.columns.tolist()
rows = df.index.tolist()
print(f"Colums: {columns}, count: {len(columns)}")
print(f"Rows count: {len(rows)}")

Colums: ['name', 'age', 'city'], count: 3
Rows count: 5

In [8]:
print(df.head(3))

     name  age     city
0  Cement   17     Kyiv
1  Nikita   14    Paris
2   Kiril   19  Kharkiv

# Task2

#### У файлі CSV збережено дані про фільми: "Назва", "Жанр", "Рік", "Рейтинг".
#### Прочитайте дані з CSV у DataFrame.
#### Виведіть перші п'ять рядків таблиці.
#### Визначте загальну кількість рядків і стовпців.
#### Визначте типи даних для кожного стовпця.
#### Перевірте наявність пропусків.

In [9]:
df_from_file = pd.read_csv("films.csv")
print(df_from_file.head())

          Title           Genre  Year  Rating
0     Inception          Sci-Fi  2010     8.8
1       Titanic   Romance/Drama  1997     7.9
2    The Matrix   Sci-Fi/Action  1999     8.7
3  Interstellar    Sci-Fi/Drama  2014     8.6
4      Parasite  Thriller/Drama  2019     8.5

In [10]:
print(f"Columns count: {len(df_from_file.columns.tolist())}")
print(f"Rows count: {len(df_from_file.index.tolist())}")

Columns count: 4
Rows count: 5

In [11]:
print(df_from_file.dtypes)

Title         str
Genre         str
Year        int64
Rating    float64
dtype: object

In [15]:
for col in df_from_file.columns:
    none_values = 0
    for value in df_from_file[col]:
        if value is None:
            none_values += 1
print(f"Count of nan values: {none_values}")

Count of nan values: 0

# Task3

#### Є таблиця співробітників із колонками: "Ім'я", "Вік", "Відділ", "Зарплата".
#### Створіть DataFrame з не менш ніж п'ятьма рядками.
#### Виведіть усі рядки, де зарплата вища за 50000.
#### Відсортуйте таблицю за віком у порядку зростання.
#### Відсортуйте таблицю за зарплатою в порядку спадання.

In [17]:
df3 = pd.DataFrame({
    "Name": ["Anna", "Bogdan", "Maria", "Oleg", "Irina"],
    "Age": [28, 35, 22, 40, 30],
    "Department": ["HR", "IT", "Marketing", "IT", "Finance"],
    "Salary": [48000, 60000, 52000, 75000, 50000]
})
df3

     Name  Age Department  Salary
0    Anna   28         HR   48000
1  Bogdan   35         IT   60000
2   Maria   22  Marketing   52000
3    Oleg   40         IT   75000
4   Irina   30    Finance   50000

In [18]:
df3[df3["Salary"] > 50000]

     Name  Age Department  Salary
1  Bogdan   35         IT   60000
2   Maria   22  Marketing   52000
3    Oleg   40         IT   75000

In [19]:
df3.sort_values(by="Age")

     Name  Age Department  Salary
2   Maria   22  Marketing   52000
0    Anna   28         HR   48000
4   Irina   30    Finance   50000
1  Bogdan   35         IT   60000
3    Oleg   40         IT   75000

In [20]:
df3_2 = df3.sort_values(by="Salary")
df3_2[::-1]

     Name  Age Department  Salary
3    Oleg   40         IT   75000
1  Bogdan   35         IT   60000
2   Maria   22  Marketing   52000
4   Irina   30    Finance   50000
0    Anna   28         HR   48000

# Task4

#### Доступні дані про продажі з колонками: "Товар", "Категорія", "Ціна", "Кількість".
#### Створіть DataFrame з не менш ніж десятьма рядками.
#### Виведіть вихідний DataFrame.
#### Додайте новий стовпець "Виручка" як добуток ціни та кількості.
#### Виведіть оновлений DataFrame.

In [22]:
df4 = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet", "Monitor", "Keyboard", 
                "Mouse", "Headphones", "Printer", "Webcamera", "Speaker"],
    "Category": ["Electronics", "Electronics", "Electronics", "Electronics", "Accessories",
                 "Accessories", "Accessories", "Electronics", "Electronics", "Accessories"],
    "Price": [1200, 800, 500, 300, 50, 25, 75, 200, 80, 150],
    "Quantity": [5, 10, 7, 6, 20, 50, 30, 3, 15, 12]
})
df4

      Product     Category  Price  Quantity
0      Laptop  Electronics   1200         5
1       Phone  Electronics    800        10
2      Tablet  Electronics    500         7
3     Monitor  Electronics    300         6
4    Keyboard  Accessories     50        20
5       Mouse  Accessories     25        50
6  Headphones  Accessories     75        30
7     Printer  Electronics    200         3
8   Webcamera  Electronics     80        15
9     Speaker  Accessories    150        12

In [23]:
df4["Revenue"] = df4["Price"] * df4["Quantity"]
df4

      Product     Category  Price  Quantity  Revenue
0      Laptop  Electronics   1200         5     6000
1       Phone  Electronics    800        10     8000
2      Tablet  Electronics    500         7     3500
3     Monitor  Electronics    300         6     1800
4    Keyboard  Accessories     50        20     1000
5       Mouse  Accessories     25        50     1250
6  Headphones  Accessories     75        30     2250
7     Printer  Electronics    200         3      600
8   Webcamera  Electronics     80        15     1200
9     Speaker  Accessories    150        12     1800

# Task5

#### Є список студентів із зазначенням: "Ім'я", "Курс", "Оцінка".
#### Створіть DataFrame і заповніть його не менш ніж вісьмома рядками.
#### Виведіть вихідний DataFrame.
#### Обчисліть середню оцінку за кожним курсом.
#### Знайдіть максимальну та мінімальну оцінку за кожним курсом.

In [24]:
df5 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah"],
    "Course": [1, 2, 1, 3, 2, 3, 1, 2],
    "Grade": [85, 90, 78, 92, 88, 75, 95, 80]
})
df5

      Name  Course  Grade
0    Alice       1     85
1      Bob       2     90
2  Charlie       1     78
3    Diana       3     92
4    Ethan       2     88
5    Fiona       3     75
6   George       1     95
7   Hannah       2     80

In [27]:
course_av = df5.groupby("Course")["Grade"].mean()
course_min = df5.groupby("Course")["Grade"].min()
course_max = df5.groupby("Course")["Grade"].max()
print(f"Course averages: \n{course_av} \nCourse max: \n{course_max} \nCourse min: \n{course_min}")

Course averages:
Course
1    86.0
2    86.0
3    83.5
Name: Grade, dtype: float64
Course max:
Course
1    95
2    90
3    92
Name: Grade, dtype: int64
Course min:
Course
1    78
2    80
3    75
Name: Grade, dtype: int64

# Task6

#### Зібрано дані про товари та продажі у двох таблицях. Перша містить: "ID", "Назва", "Ціна". Друга містить: "ID", "Кількість".
#### Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками.
#### Виведіть обидва DataFrame.
#### Об'єднайте їх за колонкою "ID".
#### Додайте новий стовпець "Сума" як добуток ціни та кількості.
#### Виведіть підсумковий DataFrame.

In [29]:
products_df = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Laptop", "Phone", "Tablet", "Monitor", "Keyboard"],
    "Price": [1200, 800, 500, 300, 50]
})

sales_df = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Quantity": [5, 10, 7, 6, 20]
})
products_df

   ID      Name  Price
0   1    Laptop   1200
1   2     Phone    800
2   3    Tablet    500
3   4   Monitor    300
4   5  Keyboard     50

In [30]:
sales_df

   ID  Quantity
0   1         5
1   2        10
2   3         7
3   4         6
4   5        20

In [31]:
m_df = pd.merge(products_df, sales_df, on='ID')
m_df

   ID      Name  Price  Quantity
0   1    Laptop   1200         5
1   2     Phone    800        10
2   3    Tablet    500         7
3   4   Monitor    300         6
4   5  Keyboard     50        20

In [32]:
m_df["Sum"] = m_df["Price"] * m_df["Quantity"]
m_df

   ID      Name  Price  Quantity   Sum
0   1    Laptop   1200         5  6000
1   2     Phone    800        10  8000
2   3    Tablet    500         7  3500
3   4   Monitor    300         6  1800
4   5  Keyboard     50        20  1000