In [1]:
import numpy as np

In [2]:
names = np.array(["Alex", "Maria", "John", "Olga", "Max"])
scores = np.array([85, 92, 74, 60, 48])
groups = np.array(["A", "B", "A", "B", "A"])

In [3]:
print("Group A: ", scores[groups == "A"].mean())
print("Group B: ", scores[groups == "B"].mean())

Group A:  69.0
Group B:  76.0

In [4]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.7 MB 8.6 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.7 MB 7.0 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.7 MB 6.7 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.7 MB 6.7 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.7 MB 6.7 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 6.7 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 6.4 MB/s  0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

In [6]:
scores = pd.Series([85, 92, 74, 60, 48])
print(scores)

0    85
1    92
2    74
3    60
4    48
dtype: int64

In [7]:
scores = pd.Series([85, 92, 74, 60, 48], 
                   index=["Alex", "Maria", "John", "Olga", "Max"])
print(scores)

Alex     85
Maria    92
John     74
Olga     60
Max      48
dtype: int64

In [8]:
print(scores["Alex"])

85

In [9]:
print(scores.mean())

71.8

In [10]:
print(scores[scores > 70])

Alex     85
Maria    92
John     74
dtype: int64

In [55]:
df = pd.DataFrame({
    "name": ["Alex", "Maria", "John", "Olga", "Max"],
    "scores1": [85, 92, 74, 60, 48],
    "score2": [75, 82, 64, 50, 38],
    "group": ["A", "B", "A", "B", "A"]
}, index=["A1", "B2", "C3", "D4", "E5"])
print(df)

     name  scores1  score2 group
A1   Alex       85      75     A
B2  Maria       92      82     B
C3   John       74      64     A
D4   Olga       60      50     B
E5    Max       48      38     A

In [19]:
print(df.dtypes)

name          str
scores      int64
groups:       str
dtype: object

In [21]:
print(df.head(2))

     name  scores groups:
A1   Alex      85        A
B2  Maria      92        B

In [22]:
print(df.tail(3))

    name  scores groups:
C3  John      74        A
D4  Olga      60        B
E5   Max      48        A

In [23]:
print(df.info())

<class 'pandas.DataFrame'>
Index: 5 entries, A1 to E5
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      str
 1   scores    5 non-null      int64
 2   groups:   5 non-null      str
dtypes: int64(1), str(2)
memory usage: 160.0+ bytes
None

In [29]:
print(df.describe())

         scores1     score2
count   5.000000   5.000000
mean   71.800000  61.800000
std    17.977764  17.977764
min    48.000000  38.000000
25%    60.000000  50.000000
50%    74.000000  64.000000
75%    85.000000  75.000000
max    92.000000  82.000000

In [32]:
print(df["scores1"])

A1    85
B2    92
C3    74
D4    60
E5    48
Name: scores1, dtype: int64

In [33]:
print(df.score2)

A1    75
B2    82
C3    64
D4    50
E5    38
Name: score2, dtype: int64

In [34]:
print(df[["name", "scores1"]])

     name  scores1
A1   Alex       85
B2  Maria       92
C3   John       74
D4   Olga       60
E5    Max       48

# loc and iloc

In [36]:
print(df.iloc[0])

name        Alex
scores1       85
score2        75
groups:        A
Name: A1, dtype: object

In [38]:
print(df.loc["A1"])

name        Alex
scores1       85
score2        75
groups:        A
Name: A1, dtype: object

In [39]:
print(df.iloc[0:3, 0:2])

     name  scores1
A1   Alex       85
B2  Maria       92
C3   John       74

In [41]:
print(df.loc["A1":"C3", ["name", "scores1", "score2"]])

     name  scores1  score2
A1   Alex       85      75
B2  Maria       92      82
C3   John       74      64

In [43]:
print(df[::-1])

     name  scores1  score2 groups:
E5    Max       48      38        A
D4   Olga       60      50        B
C3   John       74      64        A
B2  Maria       92      82        B
A1   Alex       85      75        A

In [44]:
df.to_csv("student.csv", index=False)

In [46]:
with open("student.csv") as f:
    print(f.read())

name,scores1,score2,groups:
Alex,85,75,A
Maria,92,82,B
John,74,64,A
Olga,60,50,B
Max,48,38,A

In [47]:
df_from_file = pd.read_csv("student.csv")
print(df_from_file)

    name  scores1  score2 groups:
0   Alex       85      75        A
1  Maria       92      82        B
2   John       74      64        A
3   Olga       60      50        B
4    Max       48      38        A

In [48]:
print(df.columns)

Index(['name', 'scores1', 'score2', 'groups: '], dtype='str')

In [49]:
print(df.columns.tolist())

['name', 'scores1', 'score2', 'groups: ']

In [50]:
df["average"] = (df["scores1"] + df["score2"]) / 2
df

     name  scores1  score2 groups:   average
A1   Alex       85      75        A     80.0
B2  Maria       92      82        B     87.0
C3   John       74      64        A     69.0
D4   Olga       60      50        B     55.0
E5    Max       48      38        A     43.0

In [52]:
df.loc["F6"] = ["Sophie", 95, "B", 90, 92.5]
df

      name  scores1 score2 groups:   average
A1    Alex       85     75        A     80.0
B2   Maria       92     82        B     87.0
C3    John       74     64        A     69.0
D4    Olga       60     50        B     55.0
E5     Max       48     38        A     43.0
F6  Sophie       95      B       90     92.5

In [56]:
df.loc["D4", "group"] = "A"
df

     name  scores1  score2 group
A1   Alex       85      75     A
B2  Maria       92      82     B
C3   John       74      64     A
D4   Olga       60      50     A
E5    Max       48      38     A

In [57]:
df.loc["D4", "group"] = np.nan
df

     name  scores1  score2 group
A1   Alex       85      75     A
B2  Maria       92      82     B
C3   John       74      64     A
D4   Olga       60      50   NaN
E5    Max       48      38     A

In [59]:
df = df.drop(columns="score2")

In [60]:
df

     name  scores1 group
A1   Alex       85     A
B2  Maria       92     B
C3   John       74     A
D4   Olga       60   NaN
E5    Max       48     A